static func get_property_hint(variant_type: Variant.Type) -> PropertyHint:
	match variant_type:
		TYPE_BOOL:
			return PROPERTY_HINT_NONE
		TYPE_INT:
			return PROPERTY_HINT_NONE
		TYPE_FLOAT:
			return PROPERTY_HINT_NONE
		TYPE_STRING:
			return PROPERTY_HINT_NONE
		TYPE_VECTOR2:
			return PROPERTY_HINT_NONE
		TYPE_VECTOR2I:
			return PROPERTY_HINT_NONE
		TYPE_RECT2:
			return PROPERTY_HINT_NONE
		TYPE_VECTOR3:
			return PROPERTY_HINT_NONE
		TYPE_TRANSFORM2D:
			return PROPERTY_HINT_NONE
		TYPE_VECTOR4:
			return PROPERTY_HINT_NONE
		TYPE_COLOR:
			return PROPERTY_HINT_COLOR_NO_ALPHA
		TYPE_OBJECT:
			return PROPERTY_HINT_NONE
		TYPE_DICTIONARY:
			return PROPERTY_HINT_DICTIONARY_TYPE
		TYPE_ARRAY:
			return PROPERTY_HINT_ARRAY_TYPE
		TYPE_NODE_PATH:
			return PROPERTY_HINT_NODE_PATH_VALID_TYPES
		TYPE_CALLABLE:
			return PROPERTY_HINT_TOOL_BUTTON
		TYPE_SIGNAL:
			return PROPERTY_HINT_NONE
		TYPE_PACKED_BYTE_ARRAY:
			return PROPERTY_HINT_NONE
		TYPE_PACKED_INT32_ARRAY:
			return PROPERTY_HINT_NONE
		TYPE_PACKED_FLOAT32_ARRAY:
			return PROPERTY_HINT_NONE
		TYPE_MAX:
			return PROPERTY_HINT_NONE
		_:
			return PROPERTY_HINT_NONE
